version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: archburgers_db
    hostname: archburgers_db
    restart: "no"   # Sem restart automático por ser um serviço com fins didáticos
    environment:
      POSTGRES_DB: archburgers
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: "216hdjkasda%jhjKaA"
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: psql -U pguser -d archburgers -c 'select 1'
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  app:
    image: gomesrodris/architect-burgers:0.0.5
    container_name: archburgers_app
    restart: "no"
    environment:
      "archburgers.datasource.driverClass": "org.postgresql.Driver"
      "archburgers.datasource.dbUrl": "jdbc:postgresql://archburgers_db/archburgers?autoReconnect=true"
      "archburgers.datasource.dbUser": pguser
      "archburgers.datasource.dbPass": "216hdjkasda%jhjKaA"

      "archburgers.integration.mercadopago.apiBaseUrl": "https://api.mercadopago.com"
      "archburgers.integration.mercadopago.userId": "1898521889"
      "archburgers.integration.mercadopago.accessToken": "APP_USR-5895347274256581-071317-d4d6b7289bb3a84a0edb8388342a8c3d-1898521889"
      "archburgers.integration.mercadopago.posId": "LOJA1POS1"
      "archburgers.integration.mercadopago.notificationUrl": "http://adb05a37e59fc490cb51d499977f381f-883088565.us-east-1.elb.amazonaws.com:8090/pagamento-webhook/mercado-pago"
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
