version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: archburgers_db
    hostname: archburgers_db
    restart: "no"   # Sem restart automático por ser um serviço com fins didáticos
    environment:
      POSTGRES_DB: archburgers
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: "216hdjkasda%jhjKaA"
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: psql -U pguser -d archburgers -c 'select 1'
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  app:
    image: gomesrodris/architect-burgers:0.0.2
    container_name: archburgers_app
    restart: "no"
    environment:
      "archburgers.datasource.driverClass": "org.postgresql.Driver"
      "archburgers.datasource.dbUrl": "jdbc:postgresql://archburgers_db/archburgers?autoReconnect=true"
      "archburgers.datasource.dbUser": pguser
      "archburgers.datasource.dbPass": "216hdjkasda%jhjKaA"
    ports:
      - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
