apiVersion: apps/v1
kind: Deployment
metadata:
  name: archburgers-app-deployment
spec:
  selector:
    matchLabels:
      app: archburgers-app
  replicas: 3
  template:
    metadata:
      labels:
        app: archburgers-app
    spec:
      containers:
        - name: archburgers-app-container
          image: gomesrodris/architect-burgers:0.0.3-beta
          ports:
            - containerPort: 8090
          env:
            - name: "archburgers.datasource.driverClass"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.driverClass"
            - name: "archburgers.datasource.dbUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbUrl"
            - name: "archburgers.datasource.dbUser"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbUser"
            - name: "archburgers.datasource.dbPass"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbPass"


