name: app-test-and-build
run-name: Packaging application
on:
  push:
    branches:
      - main
      - pipeline_test_dest # Temporary - testing

jobs:
  mvn-install-with-libs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven Install and Copy libraries
        run: mvn -DskipTests install dependency:copy-dependencies
      - name: Prepare app directory
        run: mkdir ./docker/temp_libs && cp ./modules/web-app/target/architect-burgers-webapi-*.jar ./docker/temp_libs/ && cp ./modules/web-app/target/lib/* ./docker/temp_libs/
      - name: Archive app directory
        uses: actions/upload-artifact@v4
        with:
          name: app-libs-dir
          path: ./docker/temp_libs/*
          retention-days: 1
      - id: OutputProjectVersion
        run: echo "project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
    outputs:
      project_version: ${{ steps.OutputProjectVersion.outputs.project_version }}

  build-docker-image:
    needs: mvn-install-with-libs
    runs-on: ubuntu-latest
    env:
      PROJECT_VERSION: ${{ needs.mvn-install-with-libs.outputs.project_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: app-libs-dir
          path: ./docker/temp_libs/
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/architect-burgers:latest,${{ vars.DOCKERHUB_USERNAME }}/architect-burgers:${{env.PROJECT_VERSION}}
