name: verify-project-on-pull-request
run-name: Verifying on PR - ${{github.event.pull_request.title}}
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  mvn-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven Verify
        run: mvn verify
